<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="page group test" duration-ms="0" started-at="2018-06-15T13:15:31Z" finished-at="2018-06-15T13:15:31Z">
    <groups>
    </groups>
  </suite> <!-- page group test -->
  <suite name="TestNG tests" duration-ms="7360" started-at="2018-06-15T13:15:24Z" finished-at="2018-06-15T13:15:31Z">
    <groups>
      <group name="page">
        <method signature="IndependentTest.pageTest()[pri:0, instance:tests.basicTests.IndependentTest@2ac1fdc4]" name="pageTest" class="tests.basicTests.IndependentTest"/>
      </group> <!-- page -->
    </groups>
    <test name="Independent Test" duration-ms="7360" started-at="2018-06-15T13:15:24Z" finished-at="2018-06-15T13:15:31Z">
      <class name="tests.basicTests.IndependentTest">
        <test-method status="PASS" signature="loadState()[pri:0, instance:tests.basicTests.IndependentTest@2ac1fdc4]" name="loadState" is-config="true" duration-ms="6312" started-at="2018-06-15T16:15:24Z" finished-at="2018-06-15T16:15:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadState -->
        <test-method status="PASS" signature="pageTest()[pri:0, instance:tests.basicTests.IndependentTest@2ac1fdc4]" name="pageTest" duration-ms="493" started-at="2018-06-15T16:15:30Z" finished-at="2018-06-15T16:15:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at tests.basicTests.IndependentTest.pageTest(IndependentTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1289)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at runner.TestRunner.main(TestRunner.java:29)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageTest -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:tests.basicTests.IndependentTest@2ac1fdc4]" name="afterClass" is-config="true" duration-ms="542" started-at="2018-06-15T16:15:30Z" finished-at="2018-06-15T16:15:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- tests.basicTests.IndependentTest -->
    </test> <!-- Independent Test -->
  </suite> <!-- TestNG tests -->
</testng-results>
